server:
  port : 8080

shared:
  file:
#    path: /Users/dbontch/workspace_git/kstate/data
    path: /shared-state
    name: kstate.txt


logging:
  level:
    root: INFO
    org.springframework.web: TRACE
